apiVersion: v1
kind: Secret
metadata:
    name: homelable
stringData:
    admin-password: ENC[AES256_GCM,data:pN6UmFdMphT3YCBVKbxEMTyJdU537cBQ,iv:ektw+H3XDsyeV84Kf9ZVSprKM+e8EswfGlgUWBwA+lo=,tag:rG5OQE4zXJOVsbhzn7/ITQ==,type:str]
    admin-password-hash: ENC[AES256_GCM,data:g2Xm2dOuMVJyrIlOPjtxk89EiY18JJCa/BuvT3YDA7JvaSf5c2/uRlqVxTX3ATXEqxjeN4jeTiA5qCB1,iv:TefeUrufHhUrX7f5IyQeQ0ZU5PpGoFrr6PMUshCaPHs=,tag:WTYk0DxyCwUkh/VS3Y5ATg==,type:str]
    secret-key: ENC[AES256_GCM,data:DSmubxDFJkCM48NCw8ZagszxSQ9NR5i78UtSlBpAeFTc7b3gWisnRQ14WJxe4p7VO49HNB6syk3lATPqcxFOTg==,iv:OVy5n0cpgEM+qZwn59vNjCWPMFqTycbnHjy5srO3r8U=,tag:OZsgFvKtMpLvPwUeWRzMgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVnFUQ2hxVGg2SCs0bGtj
            V2lKbHhpajFKSXBWQStZVy9helZvTUpvNmo0CjJsSGQ0UUJiVHVNb1ZJRmNqZ0Zr
            OHR4QW1vMmhyVmd3SjkzTWxlK2RaakUKLS0tIGJKTm1yYkFKNVNnc0dhQ21ZblVR
            dkh2UGd6Y0JTcjd2c0VaSUY5K09vekkK38SYpqyvVdCKpQMGnUyws2DIwPZl2dim
            NjQhQIm+XRWqWZ+rFiB7BMPi6gUTshOlPEaDJHySCvd4M9Jx2x1+SA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uzygqz0hgepvwphdrsualggykr8wpesulf29vphwzhr6ttxafhqmsjpgs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU0paRUYzN09rbmVaYTVn
            UGkvelZNbmlwcTF2Y29SL293UUt6UEVFU3k4CmovYXdic0hzY3hZYmhxYThWNjR4
            dFZwL0R0ZHNCYytLbWtJZ2VCdUhRcWMKLS0tIEFDUGJKYWpyNkNDSGg1Ti8ydmla
            ZlpOa2Y0U0h5TVJPRTN5em5uUytXRTgKngjkTxGhG4Z0j6GPAwsJsxmsLSvHHe4X
            htqtapHS425SP8dukeqsQJ/JaQIpKOsWAoZB3wioX9qs5aP5LYoaGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pme5neke5tpnfllq03gmp7595ldn3azkaw8qna557t0r94f604lsg2yluv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T16:51:00Z"
    mac: ENC[AES256_GCM,data:38mZeeiBbTsu24tI4YBX+kkxaJhIwNXIprpiseYqK9WQaHchBvxOJKP4WPRj924e1AEpYJCLA/iGSyI3a0ccN/L2ULNHT1yFIvKO5iBNc6NsOSktr/R+cyZQYe+bs/61Zi6TwOafbvG62UE1sd9mnqsRozzB3TicNy2++kV8YRw=,iv:uXhr9O32GiEWgS9GbbgoDz3/rPXJkhhci4+cTmGenmk=,tag:fIuXJOjDsqJwWN6pMMxEmw==,type:str]
    version: 3.13.3
