apiVersion: v1
kind: Secret
metadata:
    name: multica-secrets
    namespace: multica
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:7SKufrnGgJDRjF8H+YJIx9ipxlGzJ8bIWMdz65ctczudqOkAZvhlrxGsBd5IAhSXcpiU99T/iqCZdSkc0M2iQA==,iv:Pidx4vGh86f1ZwdHOq4VsjlSWO40goxGyDD5K0oH+MY=,tag:CF/H7UotpyLESOLxQRQwjA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cIJASV7XkUmpRZJiKFtaUGKt71iCxrHDioDGpEOISMc=,iv:mnyvHQ+MnrNHS0E4t7uMBoioKoWU5UFHvuB0Oyv1mj4=,tag:nYVb1QuZgKoWi5pNmjcXAQ==,type:str]
    RESEND_API_KEY: ""
    GOOGLE_CLIENT_SECRET: ""
    CLOUDFRONT_PRIVATE_KEY: ""
    MULTICA_DEV_VERIFICATION_CODE: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWEtRYkxvVkZaSGlZS1Fw
            RjY0Z3A1WFF1QTg0VURzakNIU2o0bDdha2lzClhyT3BEc1h5S3kxVkl6TmFmSGhB
            UzlLMXBXZmR2UTJPb3JJdTk5SFZpSmMKLS0tIFpQSmRMcmMzL092YytPaEdXVGIv
            aS9KVndWYjl6UFhzL3hMTGczMjRpYzAK+W6zrpOB6OMb4ozYEbd/hqLS6i3t4QgP
            oTa2X2NgFEhONg2ywkRMRDG8peZw5xH1cEsKOsn3n3NbB5IkcBuPxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uzygqz0hgepvwphdrsualggykr8wpesulf29vphwzhr6ttxafhqmsjpgs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUHNSR0Z2ejBETXhiOC9W
            RHhBNzlGNmIrTUJNbTQxa29LUWZYeThBalJrClJhYS9rc0NsYlNmcWd2dWNCRmNJ
            VlVEZVErSVhLQ2x3K2hVZS9SS0kzM1UKLS0tIDRxbEpGYktkcUo5Vm9rMU14QS9X
            dzIvZFNWUDM5MUVQOGtGcXMwR0pHL28Kz1v40MQXcQoCYe7V/6845opL5bMyZy3B
            9azJ8qmyhxeu/GdmTP/jEvzCizDxdhYnPFseYsHgLhj6PLttbWljEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ddunl737fwmcvp3lmcyymuw9ac8pcjf5h0pfu2ajhsd03xwmvdpq7gc9zn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T16:43:10Z"
    mac: ENC[AES256_GCM,data:1FKuP9DogI0hO5VGfGlaADMKG8FPr/zXhuSZ8BLN/2wPDKakbUcyBZgTlOEFpbFMVE1WGRsbZgTLusjvRA8o//ehZIrOu2m/V+LHLLkN+MVtSFwt5JzqYuKbziTSXnJDP2k9tvIpR4tx5BnaDTVawXJgrQSRxiH79G00/bwLIuI=,iv:MWwi1nadHMoW0hQWEZtjwMwPYTkr/KtoMCC1vyYiiNY=,tag:GUZ9qAWpTQEMlinTVeYZQw==,type:str]
    version: 3.13.3
