apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-pia
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:h/bbPiSCfz0=,iv:kewvtG11TjH+nHPES9ZN8zIpdgPBQ5E8VLT8ctvpzCs=,tag:u9j6T3V6A/pNI9UPSzO03Q==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:chE76Is+had8,iv:pbb9FVBxyqbtu4BonDPgkQRuHyczoNJ0bqhZ/aSBO74=,tag:g7kANgXoiAW60mZYkkmcZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWjFsbit0T0xkNWV2a0Rr
            bkVCaFhaUXRXRStNbzl2OVlNYkx3RW4vVUMwClVGTEp2c3lQN2c4WFJTLzJ5YTEx
            b2FoU0N3cDJadU1zZWIzT25FbmUxWDAKLS0tICtSNng2dG5mZVJ2VGhEbTNIQnd5
            MjVlRkNJSXFaUXoyM3Z6UWJRTktLM2MKKEOmDvbjxo0Uj8x2VrYRRMQDR2RAkrqy
            2KdWEtgc55JVGdp3aQk7nR4HePOey5EsjRnvhSgZ6ejk90yd11HvBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uzygqz0hgepvwphdrsualggykr8wpesulf29vphwzhr6ttxafhqmsjpgs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU05NK2dNcE1ZczRtR04y
            ZytyakNwUG5XN2daeWlFYkhNZHo0N3FjL3hZCmpPTGRxc2wxRlprd0pWQ3lkMVYr
            ZVR1ZDRiQzB6cXBkNUNwM3NWQ3FuajQKLS0tIDU5ZEZrZEdlYWdMOCtvbHBhODA4
            QzRJV2UxWWkyNFZtaGRONytwZVJCN2MK8haOnxw4R/EWwedvFDzMOKqeQO8GOlal
            zWGnV3n7FnrfMPnS4O9VcVjDjVbHudSsdm+6DiDv59yDdep8tL4+GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pme5neke5tpnfllq03gmp7595ldn3azkaw8qna557t0r94f604lsg2yluv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T09:52:13Z"
    mac: ENC[AES256_GCM,data:ANqR+f4dPFgn+FHBDOJtkCui4ealJyVcPd/S5yzeFklGcdCtGii9XQS41C+Id65UGAXdO+JcAlFUjSCO00xED5kPpciTdIyEaxS/dgLDbFas5VG2VelDWGYEHUIqUTz3c4IdHmArMoE9DvlyFuwv4pYT+lprgqJRwhT2Kln0M7c=,iv:FoLI7W3z137Oc/20eKQdAdZcvG/9X428o7YVL1s3DWs=,tag:f0Lavx+I99+Qz0SrIaDXSg==,type:str]
    version: 3.13.3
