[extend]
useDefault = true

[allowlist]
description = "sops-encrypted files and age public keys are safe to commit"
paths = ['''[^/]\.sops\.(ya?ml|json|env)$''', '''\.tfstate$''']
regexes = ['''age1[0-9a-z]{58}''']
