apiVersion: v1
kind: Secret
metadata:
    name: multica-runtime-github
    namespace: multica-runtime
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:KhQwQGjXoY2co4bwIoZBDWOkfruW+cE0NSPUFILaqRzo/xAfG8WmXw==,iv:df+bq6aunHSNM/cNoVxd9T+X+/43TFHDwdAxvQRkcJU=,tag:3Hc47Hs/yWmL3knnxcFKtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdi8rN1hpMDZVRmF3a1BK
            L1d6czl4c21rV1hJZG95NEVxUFIxSERoM1cwCldyK0Y2a3JMcGxuenNhUGJQSHBv
            L1ozTlNMODFRSVlhR3BodHUrR0hBaVkKLS0tIGdhbldvRW1JekVxYlZxaHZ5UnNx
            eTYwaStDQy9nRHBKT3dteEMyRzNTTjAKpku4ycPOQiJHBc9C3vmIBEDVMy+SWZE+
            g3A4wOAKdN0K2ZLpcjIJ+IaLhgrjy6HLdKCoSFx/egWUJ7vyEWbHYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uzygqz0hgepvwphdrsualggykr8wpesulf29vphwzhr6ttxafhqmsjpgs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdkVZNVdKUzVpYkE3bjdj
            eVViVFk4cGZGT2F3cFEvVHJ0QXRPa2JkdXprCjlxNmFwZDJ1M3RwdEtWRTJXOVdY
            ZzNSUmhMSzNKZTJONHNnMkdDM3dxdlkKLS0tIFhMQk5TeUREckZKaEdxZnBnYWU0
            TXZoTWVhNEs2clprM29PejFBNVRSMW8KFvTdUX/F5WK8PoKBJt805igNjIRpWSBK
            ltAxsCDjCfJ3P9IXaPGoa+MMmiM9Ez54XKh1fvc40DxhiXUgFdV4ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pme5neke5tpnfllq03gmp7595ldn3azkaw8qna557t0r94f604lsg2yluv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T08:24:54Z"
    mac: ENC[AES256_GCM,data:BsTEt5dJV6gd0fc4SoiTA65tf01wLLXbL8RoGWPw7NL01c8ySthTqin0b+Po1cSO55BJqKzG0GhQtrVI1R0U4f2qVhCx6xarSkcERpxMZ9JvTDaV4nO9Da69u5Wj+On7FEDMQc0eIpORbQHQn65WfowmybWcSyl5KSCKEcyJ6ZQ=,iv:CK1IxWXd2jEiZ6PwGtkFwOP4XuM+mwosSEQfEMzv2hc=,tag:ZfNOHHKliclLOKokaCx85A==,type:str]
    version: 3.13.3
