apiVersion: v1
kind: Secret
metadata:
    name: immich
stringData:
    db-password: ENC[AES256_GCM,data:fgvK5PXVb26oZ5PB95c07jAQE9LpfLfivJk1JiknCFU=,iv:fio6o/0o8dQqKxu0Sl/iVzcHCPpcMCOCGopk0zwFegM=,tag:yrpaSriS71sKHnsmSZsS3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYlc5b0g3K29CbFNsMEFz
            QnZUbitzMjM1Mkx5S0xCcVF5T3VLeml0WlRZClYzOHdUWGdFSTJ3a2xkUTRuUFA5
            bFVtWVdnclR1ZVUwODViOFViZkVUTncKLS0tIE1vKytJNlBHa3JxL0pBeG0wK2xa
            ZktLR0xKZ1Jnd0EyQ1lHNGNLWGlXT0UK6iERMfC4laetyu2KGYJ390R2rNRhO2Hz
            5EDsLHQJs5ZgrTqTho3WD4cg6M2Mwi5+ycZcfhnPhXv5Wy+dxUQ8Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uzygqz0hgepvwphdrsualggykr8wpesulf29vphwzhr6ttxafhqmsjpgs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWb2c5a1llbXA5cEs1WGUv
            ZUJkYVhzTG96Umx4Q0RQSVdmemh0OFh0TGtBClBKVitYSnl6N09URFRlT2Fra0VI
            b3hpdWxFY240c1lHcUsxZ1NCaGR2eEUKLS0tIDczTGI2WjQxMENYMjhoTklzbkUw
            SE4rTDZhOVFoOWxzbDRmSmhralZrNkkKFrYKWqb0G5wxWuueA80wwXVXsi9yIVbW
            c2DdyvTsiYJiMZFJu1uUICvVzK6V6x9SXE3AV3m1Oa3Dfp0Ayzmfmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pme5neke5tpnfllq03gmp7595ldn3azkaw8qna557t0r94f604lsg2yluv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T19:27:11Z"
    mac: ENC[AES256_GCM,data:Y68NPmi4tXm2VX4kl/KupvW/qgGzuULlhAexHaNpiM///jARbjCaHZjsaECjC/Y3PX0rqZ6OaXQ9hol6jOYfH+IYNP7BPYe2NBC4KrrqwTvkM6ML0QuOuFcRxafkNWY/9AyaGUn7X3WDUQQSvhYqvTrY8k6i1YGy7TpY5Jm6JLY=,iv:fQDYkYsenpTpWTZ5m1XHTWDsW5rYfW0m2mUAVCuIOHQ=,tag:UBc4CQelDAr/c/W14XkYWQ==,type:str]
    version: 3.13.3
