apiVersion: v1
kind: Secret
metadata:
    name: bookorbit
stringData:
    postgres-password: ENC[AES256_GCM,data:BysExaU/uct4LzYujkPsU8KOUSNBsO9ddtPYxDbfYRZE2bqLvULCu+VGU4NN4XiW,iv:D06G6tRGuSTOZ6RfXXfoAhxxuhDjSByCBMLCSCFofHA=,tag:/PZOg6VI4g5dKeR6hPpl0Q==,type:str]
    jwt-secret: ENC[AES256_GCM,data:9pLEaHu4TkN60DLGpMs/f4X2JR80zvTU9GGEx6s42ntffSfIOmuwBS8lUmnx1u/CF5DrL6qSngfanTRkgUpHXQ==,iv:dx0cObafXN53vrw4kZ2CcTrhsQ9xR/OTFP7E3zCd2UE=,tag:1FbJIPOYvdg72ATixP6tAg==,type:str]
    setup-bootstrap-token: ENC[AES256_GCM,data:Hcrlox72IC9JGxmm8sYLFJyUmokG7tjZDXsJ4lMBr/I=,iv:m8/ytkyNDQuF0nwtLkylz69wUcLZNa1gYmfuXCudFeI=,tag:K+m+s3H0/MZ0WcImVn2U0w==,type:str]
    book-request-encryption-key: ENC[AES256_GCM,data:u4k2twcxs+ToZ3eTYAdOtCHxdtE4BQR3IaV8O9NMH/kbyfuxtFyqdauEdH7vwjH7w9+HfIydSp51FEXcPIVYzg==,iv:UvG5aRMFy4wXNnk2jW1r8M3Od2Lr9S8ZGYRvD1eqZzg=,tag:Bhf7zVAmk6dC+wvzZb/FVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNFJIQTB0YVBNYlduN3gy
            OUVFM0YzS0NtVm1NYWtaZGY4cWRHcUxwQzBrClBJR01wVE1Ea0pEcHhLZ2NwOUNm
            MlpRSWo4Y1YwYzdnbko2Y2kyYVFqZWsKLS0tIFk5UFhKd3JRL0FReXVGQzVTVzdp
            QldVZEw2YkY4cjVqQ3Erem9hZ1VUSUEK41/Pqy7uGlcJC7SzYQzv9We+X9bQe7K5
            AvMlO4zVSe9lqM60XYvBk6vKkEOGo4twZvSHaCIRPphhlaGcJTrRCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uzygqz0hgepvwphdrsualggykr8wpesulf29vphwzhr6ttxafhqmsjpgs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTV0lsVHM0c2VWbmJDRkhW
            R0dsWUpRNGJVOHFKTDM3N1orSERya0ZvNnk4CjBOdytVcitjMFFjSGhrQ2ZreVZK
            a1BLSFVuMVU1Q09ySVhRK1BSZWJSVk0KLS0tIDRQT3I1ZFRjNVJFaUo2NzBqempu
            a3pZcHQyMlFhT2Q5ZWl1RUx1d3NEeU0KRL6LOTo4n4x5G2axqIi4TCzmrXzVmGvr
            gfecJ52yCOrJJLzQw1tVxVjYzAFCuxIZSTRM0EvRZRAWSnh2dHA36A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pme5neke5tpnfllq03gmp7595ldn3azkaw8qna557t0r94f604lsg2yluv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:50:21Z"
    mac: ENC[AES256_GCM,data:iQLjsqaAz1/W2eBl8PPw6/X0hRCGuejn2pZJriSla+6GBgregNYUshxOHeGhEmwjDdgpX9nEp7R+85oQF7t+fTJ1wTBnkaBZFcTkzV/Wot2A9MorGpJSx5QYm9xFtQJ1Wl0o/GH+kqiTSbFNzLHue3RvWX6y2N7aGw4XXNMoc30=,iv:dJ815MSok1Lpt2H0UZy9/ATF7MTqYy4/bP7jTrSvfE8=,tag:cI4GOg2fFpCV3XmehKKSUg==,type:str]
    version: 3.13.3
