all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.0.18
    lxc:
      hosts:
        adguard:
          ansible_host: "{{ guests.adguard.ip }}"
        jellyfin:
          ansible_host: "{{ guests.jellyfin.ip }}"
  vars:
    ansible_user: root
