apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - grafana-admin.sops.yaml
  - telegram.sops.yaml
  - victoria-metrics.yaml
  - blackbox-exporter.yaml
