apiVersion: v1
kind: Secret
metadata:
    name: ntfy
stringData:
    url: ENC[AES256_GCM,data:4lKYw5+nBKmOO3Pbpfa5U0Yg/zGqjqMX9PWp7N9byu362JzIFFeW0wQerM7QUJz5qe56M5WGcRXoLDZ7U8t9kwEFsCLpafMbEwMdOIap,iv:KSt4EI8OKaSWxVSzH6DkhnCBPH4w+M/GcpHg5Gg4KT4=,tag:nljYx2W5byuf3878efax3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVWZLbGYwNk5TT3JrakFE
            NzlhajlSTzZNSytTZGRrQmdXWmFBRnhzV0c0Cm5IcExZWVhGZS94K0tINmhrMEV5
            VldWSjNGQVl4Um5Xc0ovQy9ScUh6SFkKLS0tIG9GZkRyVjk2RzFFOU9jUnFUSlBp
            UjRUT202NjA4cWlpd1Y5MXFVNEs0RnMKlyTFE4tcSSsKfGWMNfGJE/41RFfXuBp9
            oy25nMN6OhEvy8BqK1Sx9CMe7ehQMlOlrDivhrhVq7Mwnw68MOpqUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14uzygqz0hgepvwphdrsualggykr8wpesulf29vphwzhr6ttxafhqmsjpgs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZVpNWmxtOEk1SEJqMC9t
            UENGM0phZDNmOHRzTlRaN2xub2pwNS9FcDI4CnBMMERxQnIwdUE2TFE5RGkxanNW
            RG9OOUlNV1NFb0I4S2p4Vy9LcWRJL2sKLS0tIHRIOFFOWHdDeHVNQnVrdGs1aE44
            TnRYR3FNb0RXOEQrdVV6Mk9IcVFua2MKQEIqocLqU9ytZlGG0iBzDwl09O8vURr/
            J302LUlcGR8zRHiSh7H6fKXYMPE1lxVUVQwJQ22NXwS8A/sdHQ0wQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pme5neke5tpnfllq03gmp7595ldn3azkaw8qna557t0r94f604lsg2yluv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T16:34:17Z"
    mac: ENC[AES256_GCM,data:3r/zzMid6hEJvo2QBp6PiagLVXAJ32gbsNK5cSqWqMYr5ZB9SRT9WOEKupE2N+DiaFGMAhQpvh4gudRSMgplvHU2AL1xZ4Jv7ytddzGyb3K8Xe3+OUYmwfbFNV6WCh091MzgZ3hNz4m8h3Pjdg541jlv6q5dMAN/AKq8UFKZu5w=,iv:h2egyojLWXJgjFohcVijMcDn7W1j6h33KVQEmjdudic=,tag:wghoKfnywX9Ac20j3Nmg+A==,type:str]
    version: 3.13.3
